apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapp
  labels:
    app: loginapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loginapp
  template:
    metadata:
      labels:
        app: loginapp
    spec:
      containers:
      - name: loginapp
        image: signin/loginapp:tagVersion
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
